# pylint: skip-file

"""Add docs table

Revision ID: 60b3e731d134
Revises: 
Create Date: 2025-06-09 13:00:25.990292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60b3e731d134'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_id'), 'docs', ['id'], unique=False)
    op.alter_column('payloads', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_payloads_created_at'), table_name='payloads')
    op.drop_index(op.f('idx_payloads_deleted'), table_name='payloads')
    op.drop_index(op.f('idx_payloads_platform'), table_name='payloads')
    op.drop_index(op.f('idx_payloads_tags'), table_name='payloads', postgresql_using='gin')
    op.drop_index(op.f('idx_payloads_title'), table_name='payloads', postgresql_using='gin')
    op.create_index(op.f('ix_payloads_id'), 'payloads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payloads_id'), table_name='payloads')
    op.create_index(op.f('idx_payloads_title'), 'payloads', [sa.literal_column("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_payloads_tags'), 'payloads', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_payloads_platform'), 'payloads', ['platform'], unique=False)
    op.create_index(op.f('idx_payloads_deleted'), 'payloads', ['deleted'], unique=False)
    op.create_index(op.f('idx_payloads_created_at'), 'payloads', ['created_at'], unique=False)
    op.alter_column('payloads', 'tags',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index(op.f('ix_docs_id'), table_name='docs')
    op.drop_table('docs')
    # ### end Alembic commands ###
