name: Daily Flake8 Code Scan

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  flake8-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Get today's commits in app/
        id: get_commits
        run: |
          COMMITS=$(git log --since="midnight" --pretty=format:"%H" -- app)
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV

      - name: Install flake8
        if: env.COMMITS != ''
        run: pip install flake8

      - name: Lint with Flake8
        if: env.COMMITS != ''
        run: flake8 app --format=default --output-file=flake8-report.txt || true

      - name: Upload Flake8 report as artifact
        if: env.COMMITS != ''
        uses: actions/upload-artifact@v4
        with:
          name: Flake8-report
          path: flake8-report.txt

      - name: Install Black formatter
        if: env.COMMITS != ''
        run: pip install black

      - name: Run Black formatter
        if: env.COMMITS != ''
        run: black app

      - name: Create and checkout format branch
        if: env.COMMITS != ''
        run: git checkout -b auto/format-flake8-${{ github.run_id }}

      - name: Commit formatted code
        if: env.COMMITS != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(flake8): auto-format code via GitHub Actions"
          branch: auto/format-flake8-${{ github.run_id }}
          push_options: '--force'
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request for auto-format
        if: env.COMMITS != ''
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(flake8): auto-format code via GitHub Actions"
          branch: auto/format-flake8-${{ github.run_id }}
          title: "Auto-format code via Flake8"
          body: "This PR was created automatically by GitHub Actions to format code using Flake8 (Black)."
          base: main

      - name: Generate dated lint trend report
        if: env.COMMITS != ''
        run: |
          today=$(date +'%d-%m-%Y')
          dir="python-trend"
          mkdir -p "$dir"
          trend_file="$dir/$today.md"
          echo "| Date | Error Count |" > "$trend_file"
          echo "|------|-------------|" >> "$trend_file"
          if [ -f flake8-report.txt ]; then
            ERRORS=$(cat flake8-report.txt | wc -l)
            echo "| $today | $ERRORS |" >> "$trend_file"
          fi
          echo "trend_file=$trend_file" >> $GITHUB_ENV

      - name: Upload Flake8 trend report as artifact
        if: env.COMMITS != ''
        uses: actions/upload-artifact@v4
        with:
          name: Flake8-trend-${{ env.trend_file }}
          path: ${{ env.trend_file }}

      - name: Commit trend report to trend-reports branch
        if: env.COMMITS != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git ls-remote --exit-code --heads origin trend-reports ; then
            git checkout -b trend-reports
            git push origin trend-reports
          else
            git fetch origin trend-reports:trend-reports
            git checkout trend-reports
          fi
          cp "${{ env.trend_file }}" .
          git add "${{ env.trend_file }}"
          git commit -m "chore(trend-report): add Flake8 lint error trend for ${{ env.trend_file }} [automated]" || echo "No changes to commit"
          git push origin trend-reports

      - name: Create issues for Flake8 findings
        if: env.COMMITS != ''
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { repo, owner } = context.repo;
            const commitSha = process.env.GITHUB_SHA;
            const today = new Date().toISOString().split('T')[0];

            async function issueExists(title) {
              const { data: issues } = await github.rest.issues.listForRepo({
                owner,
                repo,
                state: 'open',
                labels: 'bug,automated-scan'
              });
              return issues.some(issue => issue.title === title);
            }

            if (fs.existsSync('flake8-report.txt')) {
              const lines = fs.readFileSync('flake8-report.txt', 'utf-8').split('\n').filter(Boolean);
              for (const line of lines) {
                const title = `Flake8: Issue found [${today}]`;
                if (!(await issueExists(title))) {
                  await github.rest.issues.create({
                    owner,
                    repo,
                    title,
                    body: `**Detail:** ${line}\n**Commit:** ${commitSha}\n**Date:** ${today}`,
                    labels: ['bug', 'automated-scan']
                  });
                }
              }
            }
