# .github/workflows/python-ci.yml

name: Python Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      DATABASE_URL: postgresql+asyncpg://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@localhost:5432/${{ secrets.DB_NAME }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install mypy pylint pytest

    - name: Lint with pylint
      run: |
        pylint backend/app backend/main.py --exit-zero

    - name: Type check with mypy
      run: |
        mypy backend/app

    - name: Run Alembic migrations
      run: |
        cd backend
        PYTHONPATH=. alembic upgrade head

    - name: Run pytest (if you add tests)
      run: |
        pytest backend/tests || true  # Remove '|| true' to fail the build on test failures

